<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression &amp; Interpretability Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression &amp; Interpretability Challenge</h1>
<p class="subtitle lead">Don’t Trust Linear Models - The Perils of Non-Linearity</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This analysis examines how linear regression can produce misleading results when underlying relationships are non-linear. Using a dataset with a known true relationship, I evaluate how different model specifications affect interpretation, particularly when using proxy variables and “controlling for” additional factors.</p>
<section id="the-true-relationship" class="level3">
<h3 class="anchored" data-anchor-id="the-true-relationship">The True Relationship</h3>
<p>We define three variables:</p>
<p><span class="math display">\[
\begin{aligned}
A &amp;\equiv \textrm{Anxiety Level measured by fMRI activity}\\
S &amp;\equiv \textrm{Stress Level measured by cortisol level in blood}\\
T &amp;\equiv \textrm{\# of minutes on social media in last 24 hours}
\end{aligned}
\]</span></p>
<p>We <strong>know</strong> the true relationship among these variables:</p>
<p><span class="math display">\[
Anxiety = Stress + 0.1 \times Time
\]</span></p>
<p>This equation implies specific values in the multiple regression framework <span class="math inline">\(Anxiety = \beta_0 + \beta_1 \times Stress + \beta_2 \times Time + \epsilon\)</span>:</p>
<ul>
<li><span class="math inline">\(\beta_0 = 0\)</span> (intercept is zero)</li>
<li><span class="math inline">\(\beta_1 = 1\)</span> (coefficient on Stress is 1)</li>
<li><span class="math inline">\(\beta_2 = 0.1\)</span> (coefficient on Time is 0.1)</li>
</ul>
</section>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<div class="cell" data-execution_count="2">
<div id="tbl-observations" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Observed data with known true relationships
</figcaption>
<div aria-describedby="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Stress</th>
<th data-quarto-table-cell-role="th">StressSurvey</th>
<th data-quarto-table-cell-role="th">Time</th>
<th data-quarto-table-cell-role="th">Anxiety</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>0</td>
<td>0.0</td>
<td>0.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>8</td>
<td>9</td>
<td>2.1</td>
<td>8.21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>The dataset is constructed such that the true relationship holds exactly for every observation.</p>
<div id="cell-fig-stress-proxy" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-stress-proxy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stress-proxy-output-1.png" width="662" height="374" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: StressSurvey as a proxy for actual Stress levels
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="analysis-tasks" class="level2">
<h2 class="anchored" data-anchor-id="analysis-tasks">Analysis Tasks</h2>
<ol type="1">
<li><strong>Bivariate Regression: Anxiety on StressSurvey.</strong> Run a bivariate regression of Anxiety on StressSurvey. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<div id="ed23171b" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>-1.524000000000001 1.0470000000000002</code></pre>
</div>
</div>
<p>The estimated intercept (-1.524) and slope (1.047) suggest a strong positive relationship. However, these estimates deviate meaningfully from the true data-generating process, indicating model misspecification. Using StressSurvey as a proxy and omitting Time leads to bias, as the coefficient absorbs effects from both non-linearity and the missing variable.</p>
<p>The negative intercept further indicates misspecification. Despite appearing strong, this regression provides a misleading interpretation of the true relationship. This demonstrates that even a strong statistical relationship can be misleading when the underlying variable is a non-linear proxy.</p>
<ol start="2" type="1">
<li><strong>Visualization: StressSurvey vs Anxiety.</strong> Create a scatter plot with the regression line showing the relationship between StressSurvey and Anxiety. Comment on the fit and any potential issues.</li>
</ol>
<div id="98feb815" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-6-output-1.png" width="662" height="373" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The scatter plot shows a clear upward trend between StressSurvey and Anxiety, and the regression line fits the data closely. At first glance, this suggests a strong positive relationship.</p>
<p>However, closer inspection reveals non-linear distortions, especially at lower and higher stress levels, where the line either under- or over-predicts Anxiety. This occurs because StressSurvey is only a monotonic but non-linear proxy for true stress, and the model omits Time, which also influences Anxiety.</p>
<p>Thus, despite the high apparent fit, the regression line is misleading: it gives a false sense of a precise linear relationship while ignoring the true underlying causes.</p>
<ol start="3" type="1">
<li><strong>Bivariate Regression: Anxiety on Time.</strong> Run a bivariate regression of Anxiety on Time. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<div id="e2095f1e" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>(np.float64(-3.6801357186921675), np.float64(5.340592227020359))</code></pre>
</div>
</div>
<p>The regression of Anxiety on Time yields an intercept of -3.68 and a coefficient of 5.34. While it suggests a strong positive relationship, these estimates do not reflect the true model, where the coefficient on Time is only 0.1 and the intercept is zero.</p>
<p>By omitting Stress, the regression inflates the apparent effect of Time, absorbing variation actually caused by stress. The negative intercept further highlights model misspecification. Thus, this bivariate model gives a misleading picture of social media’s impact on anxiety. Because Time is correlated with Stress, the model incorrectly attributes Stress-driven variation in Anxiety to Time, leading to a severely inflated coefficient.</p>
<ol start="4" type="1">
<li><strong>Visualization: Time vs Anxiety.</strong> Create a scatter plot with the regression line showing the relationship between Time and Anxiety. Comment on the fit and any potential issues.</li>
</ol>
<div id="ab511020" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-8-output-1.png" width="662" height="373" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The scatter plot shows a clear misfit between the regression line and the data points:</p>
<p>Many points are far from the regression line, particularly at higher Anxiety values. This occurs because Time alone does not fully explain Anxiety; Stress is the primary driver. The slope is inflated and the intercept is strongly negative, both indicating that the bivariate model is misleading. Even though the line gives a trend, it fails to capture the true relationship:</p>
<p><span class="math display">\[
Anxiety = Stress + 0.1 \times Time
\]</span></p>
<p>Key insight: This visualization demonstrates the danger of ignoring relevant control variables — a seemingly strong linear relationship can give completely wrong conclusions when non-linearity or omitted variables are present.</p>
<ol start="5" type="1">
<li><strong>Multiple Regression: StressSurvey + Time.</strong> Run a multiple regression of Anxiety on both <strong>StressSurvey</strong> and Time. What are the estimated coefficients? How do they compare to the true coefficients?</li>
</ol>
<div id="34ab122f" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>const           0.588758
StressSurvey    1.426926
Time           -2.779944
dtype: float64</code></pre>
</div>
</div>
<p>The multiple regression produces an intercept of ~0.59, a StressSurvey coefficient of ~1.43, and a Time coefficient of ~-2.78.</p>
<p>Although the model appears statistically strong, the results are misleading: StressSurvey overstates the effect of stress, and Time shows a negative effect despite the true relationship being a small positive (0.1). This distortion occurs because StressSurvey is a non-linear proxy for actual stress, causing the regression to misattribute variation between Stress and Time.</p>
<p>Even “controlling for” Time cannot fix the bias introduced by an imperfect proxy, highlighting the danger of blindly trusting regression coefficients. The negative coefficient on Time is especially problematic because it reverses the true positive relationship, demonstrating how a flawed control variable can lead to completely incorrect conclusions.</p>
<ol start="6" type="1">
<li><strong>Multiple Regression: Stress + Time.</strong> Run a multiple regression of Anxiety on both <strong>Stress</strong> and Time. What are the estimated coefficients? How do they compare to the true relationship?</li>
</ol>
<div id="5696843d" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>const     1.110223e-16
Stress    1.000000e+00
Time      1.000000e-01
dtype: float64</code></pre>
</div>
</div>
<p>The multiple regression using Stress and Time produces coefficients that match the true relationship almost exactly:</p>
<p>Intercept ≈ 0 Stress = 1 Time = 0.1</p>
<p>Using the true Stress variable eliminates bias and accurately recovers the underlying data-generating process.</p>
<p>Key Insight:</p>
<p>“Using the true Stress variable eliminates bias and accurately recovers the underlying data-generating process. In contrast, the StressSurvey model distorts both the magnitude and direction of effects.”</p>
<ol start="7" type="1">
<li><strong>Model Comparison.</strong> Compare the R-squared values and coefficient interpretations between the two multiple regression models (Questions 5 and 6). Do both models show statistical significance in all of their coefficient estimates? What does this tell you about the real-world implications of multiple regression results?</li>
</ol>
<p>Comparing the two multiple regression models:</p>
<p>Both models produce high R² and statistically significant coefficients. However, only the model using Stress recovers the true relationship, while the StressSurvey model produces misleading estimates.</p>
<p>This highlights that statistical significance does not imply correct model specification or causal validity.</p>
<ol start="8" type="1">
<li><strong>Real-World Implications.</strong> For each of the two multiple regression models, assume their outputs were published in academic journals and then picked up by the popular press. What headline about time spent on social media and its effect on anxiety would you expect from a press outlet covering the first model? What headline for the second model? Assuming confirmation bias is real, which model is a typical parent going to believe? Which model will Facebook, Instagram, and TikTok executives prefer?</li>
</ol>
<p>Parents concerned about the negative effects of social media are more likely to believe Model 6, as it aligns with their prior beliefs that increased usage raises anxiety.</p>
<p>In contrast, social media companies would prefer Model 5, since it suggests that increased usage reduces anxiety, supporting a more favorable narrative.</p>
<p>This illustrates how confirmation bias shapes which results are accepted, regardless of model validity.</p>
<ol start="9" type="1">
<li><strong>Avoiding Misleading Statistical Significance.</strong> Reflect on this tip: split the sample into meaningful subsets (“statistical regimes”) and use graphical diagnostics for linearity rather than blind reliance on “canned” regressions. Apply this approach to the multiple regression of Anxiety on both StressSurvey and Time by analyzing a smartly chosen subset of the data. What specific subset did you choose and why? Did you get results that are both statistically significant and close to the true relationship?</li>
</ol>
<div id="7b3ca615" class="cell" data-execution_count="10">
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 3.760e+28
Date:                Fri, 10 Apr 2026   Prob (F-statistic):           2.52e-43
Time:                        13:16:03   Log-Likelihood:                 183.48
No. Observations:                   6   AIC:                            -361.0
Df Residuals:                       3   BIC:                            -361.6
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -4.0000   3.41e-13  -1.17e+13      0.000      -4.000      -4.000
StressSurvey     1.3333   1.31e-14   1.01e+14      0.000       1.333       1.333
Time             0.1000    2.2e-13   4.55e+11      0.000       0.100       0.100
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.029
Prob(Omnibus):                    nan   Jarque-Bera (JB):                1.062
Skew:                           0.707   Prob(JB):                        0.588
Kurtosis:                       1.500   Cond. No.                         600.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>To address the distortion caused by non-linearity, I focus on a high-stress subset where StressSurvey ≥ 9. In this region, the proxy behaves more linearly relative to actual Stress, reducing the mismatch between the measured and true variable.</p>
<p>I then run the same multiple regression (Anxiety on StressSurvey and Time) within this subset. The estimated coefficient on Time becomes positive and moves closer to the true value of 0.1, while the overall interpretation becomes more consistent with the true data-generating process.</p>
<p>This improvement occurs because restricting the sample reduces non-linear distortions in the proxy variable. In the full dataset, the non-linearity forces the regression to misattribute variation between StressSurvey and Time, even reversing the sign of the Time coefficient. Within the high-stress regime, this distortion is minimized.</p>
<p>This demonstrates that segmenting data into locally linear regimes can produce results that are both statistically meaningful and closer to the true relationship. Rather than relying solely on global regression models, analysts should use graphical diagnostics and subset analysis to ensure that linearity assumptions hold within the data.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>